### PR TITLE
Create Pixel-Tech.py

### PR DESCRIPTION
**Pull request by mayankgoyal-13**
This is a rock-paper-scissor game. Random library has been used here and various functions have been created. 
The game starts with a greeting message and then asks the user to enter his/her name. After that, the user chooses his hand from the list provided. The computer chooses a random hand and then validates it. After validating, the result is printed (in the form of whether the user has won or lost).

### CODE REVIEW

**Comment by someshnarwade** [comment]
There are four minor changes that would make it much better
1. Handling ValueError exception when non-integer values are passed to input
2. The program should not exit after entering an invalid number but ask player for input again
2. Asking user to play again
3. Keeping player and computer's score

Are you willing to make some or all of these changes or should I merge your PR?

**Comment by mayankgoyal-13** [comment]
I have added the point 2 and 3 you listed above. Sorry, I was not able to do point 1 and 4.

**Review by someshnarwade — APPROVED** [review]
Looks good. Merging PR

**Comment by someshnarwade** [comment]
Thank You for contributing your solution to this repository.
For point 1 if you are still interested to work on it [here's a link where you can learn how to handle exceptions in python](https://docs.python.org/3/tutorial/errors.html)

**Pull request merged**
